# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-09 15:03
from __future__ import unicode_literals

from django.db import migrations, models
import web.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(height_field='image_height', upload_to=web.models.image_path, verbose_name='image', width_field='image_width')),
                ('image_height', models.PositiveIntegerField(blank=True, null=True, verbose_name='image height')),
                ('image_width', models.PositiveIntegerField(blank=True, null=True, verbose_name='image width')),
            ],
        ),
        migrations.CreateModel(
            name='JsonTest',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('content', models.TextField()),
            ],
        ),
    ]
