# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-10 07:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20170210_0557'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matchlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('self_name', models.CharField(max_length=50)),
                ('account_name', models.CharField(default='\u9673\u66c9\u8587', max_length=50)),
                ('rating', models.CharField(max_length=50)),
            ],
        ),
    ]
