# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-13 05:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_auto_20170213_0518'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchlist',
            name='account_id',
            field=models.CharField(default='1182104795', max_length=50),
        ),
        migrations.AddField(
            model_name='matchlist',
            name='self_id',
            field=models.CharField(default='1182104795', max_length=50),
        ),
    ]
