# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-13 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_auto_20170213_0527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchlist',
            name='account_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='matchlist',
            name='self_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='registration',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
