# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-13 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_auto_20170213_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='children',
            field=models.CharField(default='\u4ee5\u5f8c\u544a\u8a34\u60a8', max_length=50),
        ),
        migrations.AlterField(
            model_name='registration',
            name='drink',
            field=models.CharField(default='\u4ee5\u5f8c\u544a\u8a34\u60a8', max_length=50),
        ),
        migrations.AlterField(
            model_name='registration',
            name='education',
            field=models.CharField(default='\u4ee5\u5f8c\u544a\u8a34\u60a8', max_length=50),
        ),
        migrations.AlterField(
            model_name='registration',
            name='eye',
            field=models.CharField(default='\u4ee5\u5f8c\u544a\u8a34\u60a8', max_length=50),
        ),
        migrations.AlterField(
            model_name='registration',
            name='faith',
            field=models.CharField(default='\u4ee5\u5f8c\u544a\u8a34\u60a8', max_length=50),
        ),
        migrations.AlterField(
            model_name='registration',
            name='figure',
            field=models.CharField(default='\u4ee5\u5f8c\u544a\u8a34\u60a8', max_length=50),
        ),
        migrations.AlterField(
            model_name='registration',
            name='hair',
            field=models.CharField(default='\u4ee5\u5f8c\u544a\u8a34\u60a8', max_length=50),
        ),
        migrations.AlterField(
            model_name='registration',
            name='income',
            field=models.CharField(default='\u4ee5\u5f8c\u544a\u8a34\u60a8', max_length=100),
        ),
        migrations.AlterField(
            model_name='registration',
            name='interest',
            field=models.CharField(default='\u4ee5\u5f8c\u544a\u8a34\u60a8', max_length=250),
        ),
        migrations.AlterField(
            model_name='registration',
            name='job',
            field=models.CharField(default='\u4ee5\u5f8c\u544a\u8a34\u60a8', max_length=50),
        ),
        migrations.AlterField(
            model_name='registration',
            name='language',
            field=models.CharField(default='\u4ee5\u5f8c\u544a\u8a34\u60a8', max_length=50),
        ),
        migrations.AlterField(
            model_name='registration',
            name='political',
            field=models.CharField(default='\u4ee5\u5f8c\u544a\u8a34\u60a8', max_length=50),
        ),
        migrations.AlterField(
            model_name='registration',
            name='race',
            field=models.CharField(default='\u4ee5\u5f8c\u544a\u8a34\u60a8', max_length=250),
        ),
        migrations.AlterField(
            model_name='registration',
            name='relationship',
            field=models.CharField(default='\u4ee5\u5f8c\u544a\u8a34\u60a8', max_length=50),
        ),
        migrations.AlterField(
            model_name='registration',
            name='smoke',
            field=models.CharField(default='\u4ee5\u5f8c\u544a\u8a34\u60a8', max_length=50),
        ),
        migrations.AlterField(
            model_name='registration',
            name='sport',
            field=models.CharField(default='\u4ee5\u5f8c\u544a\u8a34\u60a8', max_length=250),
        ),
        migrations.AlterField(
            model_name='registration',
            name='sport_habbit',
            field=models.CharField(default='\u4ee5\u5f8c\u544a\u8a34\u60a8', max_length=50),
        ),
        migrations.AlterField(
            model_name='registration',
            name='star',
            field=models.CharField(default='\u4ee5\u5f8c\u544a\u8a34\u60a8', max_length=10),
        ),
        migrations.AlterField(
            model_name='registration',
            name='tag',
            field=models.CharField(default='\u4ee5\u5f8c\u544a\u8a34\u60a8', max_length=250),
        ),
        migrations.AlterField(
            model_name='registration',
            name='wantchild',
            field=models.CharField(default='\u4ee5\u5f8c\u544a\u8a34\u60a8', max_length=50),
        ),
    ]
