# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-13 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_auto_20170213_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='tag',
            field=models.CharField(max_length=250),
        ),
    ]
