# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-14 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_auto_20170213_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='starlist',
            name='star_id',
            field=models.CharField(default='32', max_length=50),
        ),
    ]
