# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-15 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_auto_20170215_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchlist',
            name='star_id',
            field=models.CharField(default='29', max_length=50),
        ),
    ]
